name: 'checkout-onlyrequiredfiles'
description: 'Checkout only certain files'
author: 'Puzits'

branding:
  icon: 'download'
  color: 'blue'

inputs:
  files:
    description: 'Files to checkout from the repo'
    required: true
  token:
    description: 'A Github Private Access Token'
    default: ${{ github.token }}
    required: false
  branch:
    description: 'Branch to checkout files from'
    required: false
  repository:
    description: 'Repository to checkout'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
