# This is a basic workflow that is manually triggered

name: Tenant job workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs: 
      tenantName:
        type: string
        description: Step to executed
        default: 'automationdevmt.icertis.com'
        required: true
      skipBussinessAPI:
        type: string
        description: Skip Bussiness API
        default: 'false'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  send-mail-job:
   runs-on: ubuntu-latest
   env:
    tenantName: ${{ inputs.tenantName }}
    skipBussinessAPI: ${{ inputs.skipBussinessAPI }}
    
   steps: 
   - name: ✨ Send email, you star
     uses: dawidd6/action-send-mail@v3
     with:
      server_address: smtp-mail.outlook.com
      server_port: 587
      username: puzitsingh@outlook.com
      password: ${{ secrets.MYPASSWORD }}
      subject: Please review the deployment
      body: ${{ github.actor }} just starred deployment where we need your approval   https://github.com/puzits/checkout-onlyfilesrequired/actions/runs/${{ github.GITHUB_RUN_ID }}
      to: c-k.singh@icertis.com
      from: puzitsingh@outlook.com
  
  init-step:
   runs-on: ubuntu-latest
   env:
    tenantName: ${{ inputs.tenantName }}
    skipBussinessAPI: ${{ inputs.skipBussinessAPI }}
   environment: 
    name: env1
    url: https://github.com
    
   steps:
    - name: set-state 
      shell: pwsh
      run: | 
            $state =  [PSCustomObject]@{
                 TenantName = ${env:tenantName}
            }
            $state | Convertto-Json > artifact.json
        
    - name: Upload artifacts 
      uses: actions/upload-artifact@v3
      with:
          name: state
          path: artifact.json
        
         
  # This workflow contains a single job called "greet"
  call-powerbi-workflow:
    needs: init-step
    uses: ./.github/workflows/reusablejob.yml
    if: needs.init-step.result == 'success' 
    with:
      jobname: "PowerBI"
      stepname: "step 1"
  
  call-AIML-workflow:
    needs: init-step
    uses: ./.github/workflows/reusablejob.yml
    if: needs.init-step.result == 'success' 
    with:
      jobname: "AIML"
      stepname: "step 1"
      
  call-BusinessAPI-workflow:
    needs: init-step
    uses: ./.github/workflows/reusablejob.yml
    if: needs.init-step.result == 'success' 
    with:
      jobname: "BussinessAPI"
      stepname: "step 1"
      skip: ${{ inputs.skipBussinessAPI }}
   
      
  call-WordAPI-workflow:
    needs: call-BusinessAPI-workflow
    uses: ./.github/workflows/reusablejob.yml
    if: needs.init-step.result == 'success' 
    with:
      jobname: "WordAI"
      stepname: "step 1"
